apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- todo-app/manifests/namespace.yaml
- todo-app/manifests/config.yaml
- todo-app/manifests/deployment.yaml
- todo-app/manifests/ingress.yaml
- todo-app/manifests/pvc.yaml
- todo-app/manifests/service.yaml
- todo-backend/manifests/config.yaml
- todo-backend/manifests/cronjob.yaml
- todo-backend/manifests/deployment.yaml
- todo-backend/manifests/postgres-secret.yaml
- todo-backend/manifests/postgres.yaml
- todo-backend/manifests/service.yaml
images:
- name: joyboy67/todo-app
  newName: joyboy67/todo-app
  newTag: bfdba920d030b9b71e0b3d3af4f7b5d86e85e61e
- name: joyboy67/todo-backend
  newName: joyboy67/todo-backend
  newTag: bfdba920d030b9b71e0b3d3af4f7b5d86e85e61e
