apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - todo-app/config.yaml
  - todo-app/deployment.yaml
  - todo-app/ingress.yaml
  - todo-app/pvc.yaml
  - todo-app/service.yaml
  - todo-backend/config.yaml
  - todo-backend/cronjob.yaml
  - todo-backend/deployment.yaml
  - todo-backend/postgres.yaml
  - todo-backend/service.yaml

images:
  - name: joyboy67/todo-app
    newName: joyboy67/todo-app
    newTag: "4.5"
  - name: joyboy67/todo-backend
    newName: joyboy67/todo-backend
    newTag: "4.5"
