apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- config.yaml
- deployment.yaml
- service.yaml
- pvc.yaml

images:
- name: joyboy67/log-output
  newName: joyboy67/log-output
  newTag: a19a2565bddee46152bdda3d6e5286a4ffd9349a
