apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- config.yaml
- deployment.yaml
- service.yaml
- pvc.yaml

images:
- name: joyboy67/log-output
  newName: joyboy67/log-output
  newTag: 78390ff4f87c55a8fcdf20ed3cd77b6977e9ceca
