apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-claim
  namespace: exercises
spec:
  storageClassName: log-pv
  volumeName: log-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
