apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: ping-pong-cpu
  namespace: exercises
spec:
  metrics:
    - name: namespace-cpu-usage
      initialDelay: 5m
      count: 1
      successCondition: result < 0.5
      failureLimit: 1
      provider:
        prometheus:
          address: http://prom-prometheus-server.monitoring.svc.cluster.local
          query: |
            scalar(sum(rate(container_cpu_usage_seconds_total{namespace="exercises", container!=""}[5m])))
