apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ping-pong-dep
  name: ping-pong-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ping-pong-dep
    spec:
      containers:
        - image: joyboy67/ping-pong:2.1
          name: ping-pong
