apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: todo-app-deployment
  name: todo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todo-app-deployment
    spec:
      containers:
      - image: joyboy67/todo-app:1.2
        name: todo-app
        resources: {}
status: {}
