apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: todo-app-deployment
  name: todo-app-deployment
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todo-app-deployment
    spec:
      containers:
        - image: joyboy67/todo-app:2.10
          name: todo-app
          envFrom:
            - configMapRef:
                name: todo-app-config
          volumeMounts:
            - mountPath: /app/files
              name: todo-storage
      volumes:
        - name: todo-storage
          persistentVolumeClaim:
            claimName: todo-claim
