apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base
- namespace.yaml

images:
- name: joyboy67/todo-app
  newName: joyboy67/todo-app
  newTag: 4819a4e0f1413eac916e478d5cea3a4d317c0f16
- name: joyboy67/todo-backend
  newName: joyboy67/todo-backend
  newTag: 4819a4e0f1413eac916e478d5cea3a4d317c0f16
