apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base
  - postgres-backup-cronjob.yaml
  - namespace.yaml

images:
  - name: joyboy67/todo-app
    newName: joyboy67/todo-app
    newTag: "4.5"
  - name: joyboy67/todo-backend
    newName: joyboy67/todo-backend
    newTag: "4.5"
