apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: todo-backend-dep
  name: todo-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todo-backend-dep
    spec:
      containers:
        - image: todo-backend
          name: todo-backend
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE_URL
          envFrom:
            - configMapRef:
                name: todo-backend-config
          readinessProbe:
            httpGet:
              path: /todos
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
