name: Delete environment

on:
  delete:

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b

jobs:
  delete-environment:
    if: github.event.ref_type == 'branch' && github.event.ref != 'main'
    name: Delete Branch Environment
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v3
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          project_id: ${{ env.PROJECT_ID }}
          location: ${{ env.GKE_ZONE }}

      - name: Delete Namespace
        run: |-
          TARGET_NAMESPACE="${{ github.event.ref }}"
          echo "Deleting namespace $TARGET_NAMESPACE..."
          kubectl delete namespace $TARGET_NAMESPACE || true
