name: Release application

on:
  push:
    branches:
      - "*"

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: dwk-repo
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Configure Docker
        run: gcloud --quiet auth configure-docker ${{ env.REGISTRY }}

      - name: Form Image Names
        run: |-
          echo "APP_IMAGE=$REGISTRY/$PROJECT_ID/$REPOSITORY/todo-app:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
          echo "BACKEND_IMAGE=$REGISTRY/$PROJECT_ID/$REPOSITORY/todo-backend:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build & Publish todo-app
        run: |-
          docker build --tag $APP_IMAGE ./todo-app
          docker push $APP_IMAGE

      - name: Build & Publish todo-backend
        run: |-
          docker build --tag $BACKEND_IMAGE ./todo-backend
          docker push $BACKEND_IMAGE

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v3
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          project_id: ${{ env.PROJECT_ID }}
          location: ${{ env.GKE_ZONE }}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v3

      - name: Deploy
        run: |-
          if [ "$BRANCH" = "main" ]; then
            ENV_NAMESPACE="project"
          else
            ENV_NAMESPACE="$BRANCH"
          fi

          kubectl create namespace $ENV_NAMESPACE || true
          kubectl config set-context --current --namespace=$ENV_NAMESPACE

          kustomize edit set namespace $ENV_NAMESPACE
          kustomize edit set image todo-app=$APP_IMAGE
          kustomize edit set image todo-backend=$BACKEND_IMAGE

          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/todo-app-deployment -n $ENV_NAMESPACE
          kubectl rollout status deployment/todo-backend-dep -n $ENV_NAMESPACE
          kubectl get services -o wide -n $ENV_NAMESPACE
