name: Release application

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: dwk-repo
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Keyless authentication to Google Cloud
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud --quiet auth configure-docker ${{ env.REGISTRY }}

      # Construct exact image tags using git SHA
      - name: Form Image Names
        run: |-
          echo "APP_IMAGE=$REGISTRY/$PROJECT_ID/$REPOSITORY/todo-app:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
          echo "BACKEND_IMAGE=$REGISTRY/$PROJECT_ID/$REPOSITORY/todo-backend:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      # Build and Push
      - name: Build & Publish todo-app
        run: |-
          docker build --tag $APP_IMAGE ./todo-app
          docker push $APP_IMAGE

      - name: Build & Publish todo-backend
        run: |-
          docker build --tag $BACKEND_IMAGE ./todo-backend
          docker push $BACKEND_IMAGE

      # Authenticate to GKE
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      # Deploy with Kustomize
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Deploy
        run: |-
          kustomize edit set image todo-app=$APP_IMAGE
          kustomize edit set image todo-backend=$BACKEND_IMAGE
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/todo-app-deployment -n project
          kubectl rollout status deployment/todo-backend-dep -n project
          kubectl get services -o wide -n project
